apiVersion: v1
kind: ResourceQuota
metadata:
  name: web-app-quota
  namespace: web-app
spec:
  hard:
    pods: "5"
    requests.cpu: "500m"
    requests.memory: "1Gi"
    limits.cpu: "1"
    limits.memory: "2Gi"
